name: Build and Release VRCNotify

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Extract changelog for release
        id: changelog
        run: |
          $TAG=${{ github.ref_name }}
          $CHANGELOG=$(awk -v tag="$TAG" '/^## / {if (p) exit; if ($2 == tag) p=1} p' CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run build script
        run: |
          ./build.bat

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VRCNotify-${{ github.ref_name }}
          path: ./dist/VRCNotify.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.changelog }}
          files: ./dist/VRCNotify.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}