name: Build and Release VRCNotify

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Extract changelog for release
        id: changelog
        shell: pwsh
        run: |
          $TAG="${{ github.ref_name }}"
          $CHANGELOG = Get-Content CHANGELOG.md | ForEach-Object {
            if ($_ -match '^## ') {
              if ($p) { break }
              if ($_ -match "^## $TAG") { $p = $true }
            }
            if ($p) { $_ }
          }
          echo "::set-output name=changelog::$CHANGELOG"
          echo "changelog=$CHANGELOG" >> $GITHUB_ENV

      - name: Run build script
        run: |
          ./build.bat

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VRCNotify-${{ github.ref_name }}
          path: ./dist/VRCNotify.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.changelog }}
          files: ./dist/VRCNotify.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}